# Generated by Django 2.1.4 on 2018-12-25 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='氏名')),
                ('is_staff', models.BooleanField(default=False, help_text='管理者サイトにログインできるか', verbose_name='スタッフ')),
                ('is_superuser', models.BooleanField(default=False, help_text='スーパーユーザーかどうか', verbose_name='スーパーユーザー')),
                ('is_active', models.BooleanField(default=True, help_text='ユーザーがアクティブかどうか', verbose_name='アクティブ')),
                ('dete_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
